[package]
name = "vscode_lernen"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.22.0"
tokio-postgres = "0.7.8"
tokio = { version = "1.28.0", features = ["full"] }
futures = "0.3.28"
ini = "1.3.0"
